import 'dart:math';
import '../../data/models/gossip_item_model.dart';

class GossipEngine {
  static final List<GossipItemModel Function(int inGameDay)> _gossipPool = [
    // 1. Çaycı Necati - SUV & Ticari
    (int day) => GossipItemModel(
      id: 'gossip_necati_suv_$day',
      sourceNpc: 'cayci_necati',
      sourceNpcName: 'Çaycı Necati',
      sourceAvatar: 'cayci',
      title: 'Çay Ocağı SUV Talebi',
      teaser: 'Müteahhitler masada harıl harıl 4x4 soruyor. Bir şeyler dönüyor.',
      content: 'Önümüzdeki günlerde SUV ve arazi araçlarında talep %30 artacak. Garaja çeken iyi kâr yazar.',
      cost: 2500.0,
      accuracy: 0.85,
      type: GossipType.marketTrend,
      targetSegment: 'SUV',
      inGameDay: day,
    ),
    // 2. Çaycı Necati - Sedan & Memur
    (int day) => GossipItemModel(
      id: 'gossip_necati_sedan_$day',
      sourceNpc: 'cayci_necati',
      sourceNpcName: 'Çaycı Necati',
      sourceAvatar: 'cayci',
      title: 'Kamu Tayin Dönemi Kulisleri',
      teaser: 'Memurlar bütçeyi toparlayıp C segmenti sedan aramaya başladı.',
      content: 'Dizel ve otomatik aile sedanlarına yoğun talep geliyor. Hızlı elden çıkarabileceğin temiz sedanları topla.',
      cost: 2200.0,
      accuracy: 0.80,
      type: GossipType.marketTrend,
      targetSegment: 'Sedan',
      inGameDay: day,
    ),
    // 3. Vlogger Berk - Klasik & Genç
    (int day) => GossipItemModel(
      id: 'gossip_berk_klasik_$day',
      sourceNpc: 'vlogger_berk',
      sourceNpcName: 'Vlogger Berk',
      sourceAvatar: 'vlogger',
      title: 'Sosyal Medya Klasik Furyası',
      teaser: 'Maslak tayfası 90lar arabalarını parlatıp video çekme yarışında.',
      content: 'Boğaziçi ve Nişantaşı alıcıları nostaljik sedan ve coupe araçlara yüksek teklif vermeye hazır.',
      cost: 8500.0,
      accuracy: 0.88,
      type: GossipType.rivalIntel,
      targetSegment: 'Klasik',
      inGameDay: day,
    ),
    // 4. Vlogger Berk - Spor & Hot Hatch
    (int day) => GossipItemModel(
      id: 'gossip_berk_spor_$day',
      sourceNpc: 'vlogger_berk',
      sourceNpcName: 'Vlogger Berk',
      sourceAvatar: 'vlogger',
      title: 'Pist Günü Hazırlığı',
      teaser: 'Genç tayfa yazılım atılmış hızlı hatchback avına çıktı.',
      content: 'Egzozlu, süspansiyonlu spor modellere gelen teklifler normal piyasa değerinin %20 üstüne çıkacak.',
      cost: 7500.0,
      accuracy: 0.82,
      type: GossipType.marketTrend,
      targetSegment: 'Spor',
      inGameDay: day,
    ),
    // 5. Çıkmacı İbo - Samanlık
    (int day) => GossipItemModel(
      id: 'gossip_ibo_garaj_$day',
      sourceNpc: 'cikmaci_ibo',
      sourceNpcName: 'Çıkmacı İbo',
      sourceAvatar: 'cikmaci',
      title: 'Terk Edilmiş Garaj İhbarı',
      teaser: 'Sanayinin arkasındaki depoda yıllardır yatan diri bir kasa buldum.',
      content: 'Sahibi acil nakit için kelepir fiyata devretmeye hazır. Restorasyonla iki katı kâr bırakır.',
      cost: 14000.0,
      accuracy: 0.95,
      type: GossipType.bargainTip,
      inGameDay: day,
    ),
    // 6. Çıkmacı İbo - Yedek Parça Durgunluğu
    (int day) => GossipItemModel(
      id: 'gossip_ibo_parca_$day',
      sourceNpc: 'cikmaci_ibo',
      sourceNpcName: 'Çıkmacı İbo',
      sourceAvatar: 'cikmaci',
      title: 'Hurda Girişi & Parça İndirimi',
      teaser: 'Liman gümrüğünden üç tır dolusu orijinal yedek parça indirdik.',
      content: 'Kaporta ve mekanik bakım masraflarında hurdalık indirimleri devreye girdi.',
      cost: 4000.0,
      accuracy: 0.90,
      type: GossipType.marketTrend,
      inGameDay: day,
    ),
    // 7. Usta Selim - Katran Basılmış Motorlar
    (int day) => GossipItemModel(
      id: 'gossip_selim_katran_$day',
      sourceNpc: 'usta_selim',
      sourceNpcName: 'Usta Selim',
      sourceAvatar: 'usta',
      title: 'Ustanın Röntgeni: Yağ Katkısı Hilesi',
      teaser: 'Piyasadaki bazı araçların motoruna kalın yağ basıp dumanı kesmişler.',
      content: 'İlandaki araçların şanzıman ve motor iç aşınmalarını açığa çıkarır, motor kitleme riskini önler.',
      cost: 5500.0,
      accuracy: 1.0,
      type: GossipType.hiddenDefect,
      inGameDay: day,
    ),
    // 8. Usta Selim - Şasi Düzeltme
    (int day) => GossipItemModel(
      id: 'gossip_selim_sasi_$day',
      sourceNpc: 'usta_selim',
      sourceNpcName: 'Usta Selim',
      sourceAvatar: 'usta',
      title: 'Podya ve Direk Uyarısı',
      teaser: 'Kaldırıma sert vurup şasisi gönyeden kaçmış iki araç pazarda geziyor.',
      content: 'Ekspertizde görünmeyen şasi kılcal çatlaklarını ve robotla çekilmiş podyaları doğrudan gösterir.',
      cost: 6000.0,
      accuracy: 1.0,
      type: GossipType.hiddenDefect,
      inGameDay: day,
    ),
    // 9. Noter Katibi Derya - Acil Haciz & Devir
    (int day) => GossipItemModel(
      id: 'gossip_derya_haciz_$day',
      sourceNpc: 'noter_derya',
      sourceNpcName: 'Noter Katibi Derya',
      sourceAvatar: 'noter_derya',
      title: 'Mesai Bitimi Borç Kapatma Satışı',
      teaser: 'Kredisi sıkışmış bir iş insanı bugün noter kapanmadan imza atmak istiyor.',
      content: 'Piyasa değerinin %25 altına bırakılacak temiz bir esnaf aracı pazara düşüyor.',
      cost: 9000.0,
      accuracy: 0.92,
      type: GossipType.bargainTip,
      inGameDay: day,
    ),
    // 10. Ekspertizci Kadir - Boya Mikron Hilesi
    (int day) => GossipItemModel(
      id: 'gossip_kadir_mikron_$day',
      sourceNpc: 'ekspertiz_kadir',
      sourceNpcName: 'Ekspertizci Kadir',
      sourceAvatar: 'ekspertiz_kadir',
      title: 'Vernik İnceltme Operasyonu',
      teaser: 'Tavanı macunlu aracı mikron boyayla orijinal göstermeye çalışanlar var.',
      content: 'İncelenen araçların boya kalınlık hilelerini ve orijinal parça değişimlerini sıfır hatayla raporlar.',
      cost: 4800.0,
      accuracy: 0.96,
      type: GossipType.hiddenDefect,
      inGameDay: day,
    ),
    // 11. Sigortacı Melih - Sel & Dolu Kayıtları
    (int day) => GossipItemModel(
      id: 'gossip_melih_kasko_$day',
      sourceNpc: 'sigortaci_melih',
      sourceNpcName: 'Sigortacı Melih',
      sourceAvatar: 'sigortaci_melih',
      title: 'Tramer Kaydı Şişirilmiş Dosyalar',
      teaser: 'Kaskodan para almak için tampon çiziğine ağır hasar yazdıran bir araç tespit ettik.',
      content: 'Şişirilmiş hasar kayıtlı fakat iskeleti tertemiz olan araçları kelepir fiyata kapatma fırsatı.',
      cost: 7000.0,
      accuracy: 0.90,
      type: GossipType.bargainTip,
      inGameDay: day,
    ),
    // 12. Taksici Şevket Dayı - Yakıt & LPG Trendi
    (int day) => GossipItemModel(
      id: 'gossip_sevket_lpg_$day',
      sourceNpc: 'taksici_sevket',
      sourceNpcName: 'Taksici Şevket Dayı',
      sourceAvatar: 'taksici_sevket',
      title: 'Durak Sohbeti: LPG ve Az Yakanlar',
      teaser: 'Akaryakıt zammı beklentisiyle herkes az yakan 1.3 ve 1.4 motorların peşine düştü.',
      content: 'Ekonomik şehir içi araçların el değiştirme hızı iki katına çıktı. Rafta bekletmeden satarsın.',
      cost: 3000.0,
      accuracy: 0.85,
      type: GossipType.marketTrend,
      targetSegment: 'Ekonomik',
      inGameDay: day,
    ),
    // 13. Gümrükçü Tarık - İcra & Tasfiye Partisi
    (int day) => GossipItemModel(
      id: 'gossip_tarik_tasfiye_$day',
      sourceNpc: 'gumrukcu_tarik',
      sourceNpcName: 'Gümrükçü Tarık',
      sourceAvatar: 'gumrukcu_tarik',
      title: 'Liman Sundurmasında Bekleyen İthal Araç',
      teaser: 'Vergisi ödenmeyip tasfiyeye kalan yabancı plakalı lüks bir sedan var.',
      content: 'İhale masasında piyasanın yarı fiyatına teklif verip kapatabileceğin özel bir parti.',
      cost: 16000.0,
      accuracy: 0.94,
      type: GossipType.rivalIntel,
      targetSegment: 'Lüks',
      inGameDay: day,
    ),
    // 15. Egzozcu Tayfun - Modifiyeli Varex & Yazılım
    (int day) => GossipItemModel(
      id: 'gossip_tayfun_egzoz_$day',
      sourceNpc: 'egzozcu_tayfun',
      sourceNpcName: 'Egzozcu Tayfun',
      sourceAvatar: 'tayfun',
      title: 'Cadde Trendi: Varex ve Popcorn',
      teaser: 'Maslak gençliği çift çıkış varex egzozlu hızlı hatchback arıyor.',
      content: 'Modifiye görmüş ve yazılımlı spor araçlarda talep %25 artacak. Garajdaki genç işi araçlar prim yapacak.',
      cost: 6500.0,
      accuracy: 0.86,
      type: GossipType.marketTrend,
      targetSegment: 'Spor',
      inGameDay: day,
    ),
    // 16. Kaportacı Rıza Usta - Vakumlu Göçük & Dolu Düzeltme
    (int day) => GossipItemModel(
      id: 'gossip_riza_gocuk_$day',
      sourceNpc: 'kaportaci_riza',
      sourceNpcName: 'Kaportacı Rıza',
      sourceAvatar: 'riza',
      title: 'Boyasız Göçük Onarım Fırsatı',
      teaser: 'Sanayiye yeni vakum cihazı aldık, tavanı göçük araçları boyasız sıfır gibi yapıyoruz.',
      content: 'Dolu hasarlı kelepir araçları ucuza toplayıp boyasız düzelterek galeri kârını katlama şansı.',
      cost: 4500.0,
      accuracy: 0.93,
      type: GossipType.bargainTip,
      inGameDay: day,
    ),
    // 17. Lastikçi Cengiz - 4x4 Kış Hazırlığı
    (int day) => GossipItemModel(
      id: 'gossip_cengiz_lastik_$day',
      sourceNpc: 'lastikci_cengiz',
      sourceNpcName: 'Lastikçi Cengiz',
      sourceAvatar: 'cengiz',
      title: 'Mevsim Geçişi ve SUV Talebi',
      teaser: 'Şantiyeler ve yaylacılar kış lastikli 4x4 arazi araçlarını şimdiden kapatmaya başladı.',
      content: 'SUV ve pick-up modellerine gelen alıcı teklifleri hızla tırmanıyor. Arazi araçlarını vitrine çıkar.',
      cost: 3500.0,
      accuracy: 0.88,
      type: GossipType.marketTrend,
      targetSegment: 'SUV',
      inGameDay: day,
    ),
    // 18. Döşemeci Hamdi - VIP Deri Restorasyon
    (int day) => GossipItemModel(
      id: 'gossip_hamdi_doseme_$day',
      sourceNpc: 'dosemeci_hamdi',
      sourceNpcName: 'Döşemeci Hamdi',
      sourceAvatar: 'hamdi',
      title: 'İç Kondisyon ve Makam Talebi',
      teaser: 'Hakiki nappa deri ithal ettik, eskiyen makam koltuklarını sıfırlıyoruz.',
      content: 'Lüks ve E segmenti sedan araçların iç restorasyonu ekspertiz ve müşteri puanını doğrudan tavan yaptırır.',
      cost: 5000.0,
      accuracy: 0.90,
      type: GossipType.hiddenDefect,
      inGameDay: day,
    ),
    // 19. Yazılımcı Koray - Beyin Kilometre Manipülasyonu
    (int day) => GossipItemModel(
      id: 'gossip_koray_ecu_$day',
      sourceNpc: 'yazilimci_koray',
      sourceNpcName: 'Yazılımcı Koray',
      sourceAvatar: 'koray',
      title: 'ECU Şanzıman Beyin İncelemesi',
      teaser: 'Pazarda gösterge kilometresi 120 binde ama şanzıman beyninde 350 bin yazan araçlar var.',
      content: 'Şüpheli araçların şanzıman ve ABS beynindeki gerçek çalışma saatini doğrudan tespit eder.',
      cost: 7500.0,
      accuracy: 0.99,
      type: GossipType.hiddenDefect,
      inGameDay: day,
    ),
    // 20. Elektrikçi Nazmi - Gizli Akü & Tesisat Kaçağı
    (int day) => GossipItemModel(
      id: 'gossip_nazmi_elektrik_$day',
      sourceNpc: 'elektrikci_nazmi',
      sourceNpcName: 'Elektrikçi Nazmi',
      sourceAvatar: 'nazmi',
      title: 'Kaçak Akım ve Beyin Isınması',
      teaser: 'Ses sistemi sökülürken tesisatı delik deşik edilmiş iki araç pazarda dolaşıyor.',
      content: 'Kronik elektrik ve şarj arızası olan araçları önceden haber vererek akü boşalma riskini engeller.',
      cost: 4200.0,
      accuracy: 0.94,
      type: GossipType.hiddenDefect,
      inGameDay: day,
    ),
    // 21. Boyacı Şükrü - Lokal Mikron Geçişleri
    (int day) => GossipItemModel(
      id: 'gossip_sukru_boya_$day',
      sourceNpc: 'boyaci_sukru',
      sourceNpcName: 'Boyacı Şükrü',
      sourceAvatar: 'sukru',
      title: 'Kordon Vernik Hileleri',
      teaser: 'Direkleri kesilip eklenmiş araçları vernikle gizlemeye çalışan dolandırıcılar türedi.',
      content: 'Kesme ve ekleme araçları tespit eder, ağır noter tazminatından ve itibar kaybından korur.',
      cost: 6200.0,
      accuracy: 0.97,
      type: GossipType.hiddenDefect,
      inGameDay: day,
    ),
    // 22. Rot Balansçı Erdem - Eğri Dingil Uyarısı
    (int day) => GossipItemModel(
      id: 'gossip_erdem_rot_$day',
      sourceNpc: 'rot_erdem',
      sourceNpcName: 'Rot Balansçı Erdem',
      sourceAvatar: 'erdem',
      title: 'Arka Dingil Kayıklığı',
      teaser: 'Kaldırıma sert çıkıp arka dingili yamulmuş araç test sürüşünde sağa çekiyor.',
      content: 'Yürüyen aksamdaki gizli mekanik kusurları ve rot ayarı tutmayan araçları anında listeler.',
      cost: 3800.0,
      accuracy: 0.91,
      type: GossipType.hiddenDefect,
      inGameDay: day,
    ),
    // 23. Çekici Niyazi - Otoban Arıza Kelepirleri
    (int day) => GossipItemModel(
      id: 'gossip_niyazi_cekici_$day',
      sourceNpc: 'cekici_niyazi',
      sourceNpcName: 'Çekici Niyazi',
      sourceAvatar: 'niyazi',
      title: 'Otoban Kenarı Acil Satış',
      teaser: 'Şanzımanı kilitlendiği için sahibinin yol kenarında satmaya razı olduğu bir araç aldım.',
      content: 'Çok küçük bir mekanik tamirle piyasa değerinin iki katına satılabilecek acil kelepir partisi.',
      cost: 8200.0,
      accuracy: 0.92,
      type: GossipType.bargainTip,
      inGameDay: day,
    ),
    // 24. Hurda Simsarı Cevdet - Nadir Parça Stoğu
    (int day) => GossipItemModel(
      id: 'gossip_cevdet_hurda_$day',
      sourceNpc: 'simsar_cevdet',
      sourceNpcName: 'Hurda Simsarı Cevdet',
      sourceAvatar: 'cevdet',
      title: 'Klasik Mercedes & BMW Parça Deposu',
      teaser: 'Gümrük deposundan 80ler ve 90lar orijinal stop ve tampon stoğu kapattık.',
      content: 'Klasik restorasyon projelerinde hurdalık parça maliyetlerini %40 aşağı çeker.',
      cost: 5800.0,
      accuracy: 0.95,
      type: GossipType.marketTrend,
      targetSegment: 'Klasik',
      inGameDay: day,
    ),
  ];

  /// Generates daily industry gossips available in the district (§4.6.3)
  static List<GossipItemModel> generateDailyGossips(int inGameDay) {
    // Select 4 varied gossips deterministically based on day seed with wide rotation
    final random = Random(inGameDay * 41 + 17);
    final indices = List<int>.generate(_gossipPool.length, (i) => i);
    indices.shuffle(random);

    final selected = indices.take(4).map((idx) => _gossipPool[idx](inGameDay)).toList();
    return selected;
  }
}
