// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAehaenZTKiZCfE7soktfxR4P7rYNAEx70',
    appId: '1:1033430498827:android:3c0d99352e6a680746510e',
    messagingSenderId: '1033430498827',
    projectId: 'galeriden-game-balax',
    storageBucket: 'galeriden-game-balax.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpK5pMWlOnqjtKs8MO1o2jGydKuvy8Gf8',
    appId: '1:1033430498827:ios:8b610b917a0bff7746510e',
    messagingSenderId: '1033430498827',
    projectId: 'galeriden-game-balax',
    storageBucket: 'galeriden-game-balax.firebasestorage.app',
    iosBundleId: 'com.balax.galeriden',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXOLIZqGIaUJq8fXXSgBE_X7V0LBRAKIY',
    appId: '1:1033430498827:web:eb090faff28c5e9146510e',
    messagingSenderId: '1033430498827',
    projectId: 'galeriden-game-balax',
    authDomain: 'galeriden-game-balax.firebaseapp.com',
    storageBucket: 'galeriden-game-balax.firebasestorage.app',
  );
}
