import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../../../core/localization/app_localizations.dart';
import '../../../core/services/game_sound_haptic_service.dart';
import '../../../core/utils/currency_formatter.dart';
import '../../../core/utils/notification_service.dart';
import '../../../data/models/real_estate_category.dart';
import '../../../data/models/real_estate_model.dart';
import '../../../data/models/tenant_model.dart';
import '../../../domain/usecases/real_estate_listing_narrative_engine.dart';
import '../../providers/game_provider.dart';
import '../../widgets/neo_brutal_app_bar.dart';
import '../../widgets/neo_brutal_badge.dart';
import '../../widgets/neo_brutal_button.dart';
import '../../widgets/neo_brutal_card.dart';
import 'widgets/real_estate_offers_sheet.dart';

class RealEstateListingManageScreen extends ConsumerStatefulWidget {
  final String propertyId;

  const RealEstateListingManageScreen({
    super.key,
    required this.propertyId,
  });

  @override
  ConsumerState<RealEstateListingManageScreen> createState() =>
      _RealEstateListingManageScreenState();
}

class _RealEstateListingManageScreenState
    extends ConsumerState<RealEstateListingManageScreen>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;
  late TextEditingController _priceController;
  late TextEditingController _headlineController;
  late TextEditingController _descriptionController;

  bool _isInitialized = false;
  double _customPrice = 0.0;
  Set<String> _selectedFeatures = {};
  String _selectedPackage = 'standard';
  String _selectedStrategy = 'rayic';
  List<TenantModel>? _candidates;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    if (!_isInitialized) {
      final game = ref.read(gameProvider);
      final prop = game.ownedRealEstates.firstWhere(
        (r) => r.id == widget.propertyId,
      );

      _customPrice = prop.customListingPrice ?? prop.estimatedRealValue;
      _priceController =
          TextEditingController(text: _customPrice.round().toString());

      _selectedFeatures = Set<String>.from(prop.listingFeatures);
      _selectedPackage =
          prop.listingPackage.isNotEmpty ? prop.listingPackage : 'standard';

      final defaultHeadlines =
          RealEstateListingNarrativeEngine.getHeadlinePresets(prop.category);
      final initialHeadline = prop.listingHeadline ?? defaultHeadlines.first;
      _headlineController = TextEditingController(text: initialHeadline);

      final initialDesc = (prop.listingDescription != null &&
              prop.listingDescription!.isNotEmpty)
          ? prop.listingDescription!
          : RealEstateListingNarrativeEngine.generateDescription(
              property: prop,
              headline: initialHeadline,
              selectedFeatureIds: _selectedFeatures.toList(),
            );
      _descriptionController = TextEditingController(text: initialDesc);

      final baseMonthly = (prop.estimatedRealValue *
              prop.category.dailyRentYieldRate *
              30)
          .roundToDouble();
      _candidates = TenantModel.generateCandidates(
        baseMonthlyRent: baseMonthly > 0 ? baseMonthly : 15000.0,
        count: 3,
      );

      _isInitialized = true;
    }
  }

  @override
  void dispose() {
    _tabController.dispose();
    _priceController.dispose();
    _headlineController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  Color _getGradeColor(String grade) {
    switch (grade) {
      case 'A+':
        return const Color(0xFF10B981);
      case 'A':
        return const Color(0xFF3B82F6);
      case 'B':
        return const Color(0xFFF59E0B);
      default:
        return const Color(0xFFEF4444);
    }
  }

  void _applyPricingStrategy(RealEstateModel prop, String strategy) {
    HapticFeedback.selectionClick();
    setState(() {
      _selectedStrategy = strategy;
      switch (strategy) {
        case 'kelepir':
          _customPrice =
              (prop.estimatedRealValue * 0.90 / 1000).round() * 1000.0;
          break;
        case 'rayic':
          _customPrice = prop.estimatedRealValue;
          break;
        case 'primli':
          _customPrice =
              (prop.estimatedRealValue * 1.10 / 1000).round() * 1000.0;
          break;
        case 'tok':
          _customPrice =
              (prop.estimatedRealValue * 1.25 / 1000).round() * 1000.0;
          break;
      }
      _priceController.text = _customPrice.round().toString();
    });
  }

  void _autoGenerateDescription(RealEstateModel prop) {
    HapticFeedback.selectionClick();
    final headline = _headlineController.text.trim().isNotEmpty
        ? _headlineController.text.trim()
        : RealEstateListingNarrativeEngine.getHeadlinePresets(prop.category)
            .first;

    final text = RealEstateListingNarrativeEngine.generateDescription(
      property: prop,
      headline: headline,
      selectedFeatureIds: _selectedFeatures.toList(),
    );

    setState(() {
      _descriptionController.text = text;
    });
    NotificationService.showInfo(
      context,
      context.tr('real_estate_listing_desc_auto_generate'),
    );
  }

  String _getEstimatedWaitLabel(RealEstateModel prop) {
    final fair = prop.estimatedRealValue > 0 ? prop.estimatedRealValue : 1.0;
    final ratio = _customPrice / fair;

    if (_selectedPackage == 'super') {
      return '1 Gün • Anında VIP Teklif';
    }
    if (_selectedPackage == 'featured') {
      if (ratio <= 0.93) return '1 - 2 Gün';
      if (ratio <= 1.05) return '2 - 3 Gün';
      return '3 - 4 Gün';
    }
    // standard
    if (ratio <= 0.93) return '1 - 2 Gün';
    if (ratio <= 1.05) return '2 - 4 Gün';
    if (ratio <= 1.18) return '3 - 5 Gün';
    return '4 - 7 Gün';
  }

  void _publishSaleListing(RealEstateModel prop) {
    HapticFeedback.heavyImpact();
    final game = ref.read(gameProvider);

    double packageCost = 0.0;
    if (_selectedPackage == 'featured') {
      packageCost = 25000.0;
    } else if (_selectedPackage == 'super') {
      packageCost = 60000.0;
    }

    if (packageCost > 0 && game.balance < packageCost) {
      NotificationService.showWarning(
        context,
        context.tr('real_estate_insufficient_balance_package'),
      );
      return;
    }

    final ok = ref.read(gameProvider.notifier).listRealEstateForSale(
          prop.id,
          _customPrice,
          headline: _headlineController.text.trim(),
          description: _descriptionController.text.trim(),
          features: _selectedFeatures.toList(),
          listingPackage: _selectedPackage,
        );

    if (ok) {
      GameSoundHapticService.playCashSuccess();
      NotificationService.showSuccess(
        context,
        context.tr('real_estate_manage_toast_listed'),
      );
      context.pop();
    }
  }

  void _unlistSaleListing(RealEstateModel prop) {
    HapticFeedback.selectionClick();
    ref.read(gameProvider.notifier).unlistRealEstate(prop.id);
    NotificationService.showInfo(
      context,
      context.tr('real_estate_manage_toast_unlisted'),
    );
    context.pop();
  }

  void _leaseToCandidate(TenantModel candidate, RealEstateModel prop) {
    HapticFeedback.heavyImpact();
    final ok = ref.read(gameProvider.notifier).leaseRealEstateToTenant(
          realEstateId: prop.id,
          tenant: candidate,
        );
    if (ok) {
      GameSoundHapticService.playCashSuccess();
      NotificationService.showSuccess(
        context,
        context.tr('rental_lease_success'),
      );
      context.pop();
    }
  }

  void _confirmEviction(BuildContext ctx, RealEstateModel prop) {
    HapticFeedback.selectionClick();
    showDialog(
      context: ctx,
      builder: (dialogCtx) => AlertDialog(
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12),
          side: const BorderSide(color: Colors.black, width: 2),
        ),
        title: Text(
          dialogCtx.tr('rental_evict_confirm_title'),
          style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 16),
        ),
        content: Text(
          dialogCtx.tr('rental_evict_confirm_desc'),
          style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 13),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(dialogCtx).pop(),
            child: Text(
              dialogCtx.tr('real_estate_dialog_btn_cancel'),
              style: const TextStyle(
                  color: Colors.black54, fontWeight: FontWeight.w700),
            ),
          ),
          ElevatedButton(
            onPressed: () {
              Navigator.of(dialogCtx).pop();
              final ok =
                  ref.read(gameProvider.notifier).evictTenant(prop.id);
              if (ok) {
                GameSoundHapticService.playCashSuccess();
                NotificationService.showInfo(
                  context,
                  context.tr('rental_evict_success'),
                );
                context.pop();
              }
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFFEF4444),
              foregroundColor: Colors.white,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(8),
                side: const BorderSide(color: Colors.black, width: 1.5),
              ),
            ),
            child: Text(
              dialogCtx.tr('rental_btn_evict_tenant'),
              style: const TextStyle(fontWeight: FontWeight.w900),
            ),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;
    final game = ref.watch(gameProvider);
    final prop = game.ownedRealEstates.firstWhere(
      (r) => r.id == widget.propertyId,
    );

    final totalCost =
        prop.currentPurchasePrice + prop.deedFeePaid + prop.commissionPaid;
    final netProfit = _customPrice - totalCost;
    final profitPercent =
        totalCost > 0 ? ((netProfit / totalCost) * 100).round() : 0;
    final featureGroups =
        RealEstateListingNarrativeEngine.getFeatureGroups(prop.category);
    final headlinePresets =
        RealEstateListingNarrativeEngine.getHeadlinePresets(prop.category);

    return Scaffold(
      backgroundColor:
          isDark ? const Color(0xFF0F172A) : const Color(0xFFF8FAFC),
      appBar: NeoBrutalAppBar(
        title: context.tr('real_estate_manage_app_title'),
        onLeadingPressed: () => context.pop(),
        bottom: TabBar(
          controller: _tabController,
          labelColor: const Color(0xFF2563EB),
          unselectedLabelColor: Colors.grey,
          indicatorColor: const Color(0xFF2563EB),
          indicatorWeight: 3,
          labelStyle:
              const TextStyle(fontWeight: FontWeight.w900, fontSize: 13),
          tabs: [
            Tab(text: context.tr('real_estate_manage_tab_sell')),
            Tab(text: context.tr('real_estate_manage_tab_rent')),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          // 1. NEO-BRUTALIST SATIŞ İLANI OLUŞTURMA & YÖNETME SEKMESİ
          SingleChildScrollView(
            padding: const EdgeInsets.all(16),
            physics: const BouncingScrollPhysics(),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // 1.1 Mülk Genel Bilgi & Finansman Kartı
                _buildPropertyHeader(prop, isDark),
                const SizedBox(height: 12),

                _buildFinancialOverviewCard(
                    prop, totalCost, netProfit, profitPercent, isDark),
                const SizedBox(height: 16),

                // 1.2 Mülk Özellikleri Seçimi (detaylar girme seçme olsun ekranda)
                _buildFeaturesSelectionCard(featureGroups, isDark, prop),
                const SizedBox(height: 16),

                // 1.3 İlan Başlığı & Manşet Seçimi
                _buildHeadlineCard(headlinePresets, isDark),
                const SizedBox(height: 16),

                // 1.4 İlan Detay Metni & Organik Üretici
                _buildDescriptionCard(prop, isDark),
                const SizedBox(height: 16),

                // 1.5 Fiyatlandırma Stratejisi
                _buildPricingStrategyCard(prop, isDark),
                const SizedBox(height: 16),

                // 1.6 Vitrin & Pazarlama Paketleri
                _buildMarketingPackagesCard(game, isDark),
                const SizedBox(height: 20),

                // 1.7 Aksiyon Butonları
                _buildActionButtons(prop),
                const SizedBox(height: 32),
              ],
            ),
          ),

          // 2. KİRAYA VER SEKMESİ
          SingleChildScrollView(
            padding: const EdgeInsets.all(16),
            physics: const BouncingScrollPhysics(),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildPropertyHeader(prop, isDark),
                const SizedBox(height: 14),

                // Rayiç & Getiri Özeti
                NeoBrutalCard(
                  padding: const EdgeInsets.all(14),
                  child: Column(
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text(
                            context.tr('rental_monthly_rent'),
                            style: TextStyle(
                              fontSize: 12,
                              color: isDark ? Colors.white60 : Colors.black54,
                              fontWeight: FontWeight.w700,
                            ),
                          ),
                          Text(
                            CurrencyFormatter.format(prop.dailyRentIncome * 30),
                            style: const TextStyle(
                              fontSize: 14,
                              fontWeight: FontWeight.w900,
                              color: Color(0xFF10B981),
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 6),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text(
                            context.tr('rental_daily_rent'),
                            style: TextStyle(
                              fontSize: 12,
                              color: isDark ? Colors.white60 : Colors.black54,
                              fontWeight: FontWeight.w700,
                            ),
                          ),
                          Text(
                            CurrencyFormatter.format(prop.dailyRentIncome),
                            style: const TextStyle(
                              fontSize: 14,
                              fontWeight: FontWeight.w900,
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 14),

                // Eğer kirada ise: Aktif Kiracı Kartı
                if (prop.isRented && prop.currentTenant != null) ...[
                  Text(
                    context.tr('rental_active_tenant_header'),
                    style: const TextStyle(
                      fontSize: 13,
                      fontWeight: FontWeight.w900,
                    ),
                  ),
                  const SizedBox(height: 8),
                  NeoBrutalCard(
                    padding: const EdgeInsets.all(14),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            CircleAvatar(
                              radius: 16,
                              backgroundColor:
                                  _getGradeColor(prop.currentTenant!.reliabilityGrade)
                                      .withValues(alpha: 0.2),
                              child: Icon(
                                Icons.person_rounded,
                                color: _getGradeColor(
                                    prop.currentTenant!.reliabilityGrade),
                                size: 18,
                              ),
                            ),
                            const SizedBox(width: 10),
                            Expanded(
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    prop.currentTenant!.name,
                                    style: const TextStyle(
                                      fontSize: 13,
                                      fontWeight: FontWeight.w900,
                                    ),
                                  ),
                                  Text(
                                    prop.currentTenant!.profession,
                                    style: const TextStyle(
                                      fontSize: 11,
                                      color: Color(0xFF64748B),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            NeoBrutalBadge(
                              text: prop.currentTenant!.reliabilityGrade,
                              color: _getGradeColor(
                                  prop.currentTenant!.reliabilityGrade),
                            ),
                          ],
                        ),
                        const Divider(height: 20),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Text(
                              'Aylık Kira: ${CurrencyFormatter.format(prop.currentTenant!.monthlyRent)}',
                              style: const TextStyle(
                                fontSize: 11.5,
                                fontWeight: FontWeight.w800,
                              ),
                            ),
                            Text(
                              'Depozito: ${CurrencyFormatter.format(prop.currentTenant!.depositAmount)}',
                              style: const TextStyle(
                                fontSize: 11.5,
                                fontWeight: FontWeight.w800,
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 12),
                  NeoBrutalButton(
                    text: context.tr('rental_btn_evict_tenant'),
                    backgroundColor: const Color(0xFFEF4444),
                    textColor: Colors.white,
                    onPressed: () => _confirmEviction(context, prop),
                  ),
                ],

                // Eğer kirada değilse: Kiralık İlanı Aç / Kiracı Seç
                if (!prop.isRented) ...[
                  NeoBrutalCard(
                    padding: const EdgeInsets.all(14),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Text(
                              prop.isRentalListed
                                  ? context.tr('rental_status_listed')
                                  : context.tr('rental_status_not_listed'),
                              style: const TextStyle(
                                fontSize: 13,
                                fontWeight: FontWeight.w900,
                              ),
                            ),
                            NeoBrutalBadge(
                              text: prop.isRentalListed ? 'İlanda' : 'Boş',
                              color: prop.isRentalListed
                                  ? const Color(0xFF3B82F6)
                                  : const Color(0xFF94A3B8),
                            ),
                          ],
                        ),
                        const SizedBox(height: 8),
                        Text(
                          prop.isRentalListed
                              ? 'Kiralık ilanı aktif. Teklifler Showroom sekmesine düşecektir.'
                              : 'Kiralık ilanını açarak teklif toplayabilir ya da aşağıdaki adaylardan birini hemen kiralayabilirsiniz.',
                          style: const TextStyle(
                            fontSize: 11,
                            color: Color(0xFF64748B),
                          ),
                        ),
                        const SizedBox(height: 12),
                        NeoBrutalButton(
                          text: prop.isRentalListed
                              ? context.tr('rental_btn_unlist_rent')
                              : context.tr('rental_btn_list_rent'),
                          backgroundColor: prop.isRentalListed
                              ? const Color(0xFFF59E0B)
                              : const Color(0xFF2563EB),
                          textColor: Colors.white,
                          onPressed: () {
                            HapticFeedback.selectionClick();
                            if (prop.isRentalListed) {
                              ref
                                  .read(gameProvider.notifier)
                                  .unlistRealEstateFromRent(prop.id);
                              NotificationService.showInfo(
                                context,
                                'Kiralık ilanı kaldırıldı.',
                              );
                            } else {
                              ref
                                  .read(gameProvider.notifier)
                                  .listRealEstateForRent(prop.id);
                              NotificationService.showSuccess(
                                context,
                                'Kiralık ilanı vitrine koyuldu • Teklifler Showroom sekmesine gelecektir.',
                              );
                            }
                          },
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 16),

                  Text(
                    context.tr('rental_quick_candidates_title'),
                    style: const TextStyle(
                      fontSize: 13,
                      fontWeight: FontWeight.w900,
                    ),
                  ),
                  const SizedBox(height: 8),
                  if (_candidates != null)
                    ..._candidates!.map(
                      (cand) => Padding(
                        padding: const EdgeInsets.only(bottom: 10),
                        child: NeoBrutalCard(
                          padding: const EdgeInsets.all(12),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Row(
                                children: [
                                  CircleAvatar(
                                    radius: 14,
                                    backgroundColor:
                                        _getGradeColor(cand.reliabilityGrade)
                                            .withValues(alpha: 0.2),
                                    child: Icon(
                                      Icons.person_outline_rounded,
                                      color:
                                          _getGradeColor(cand.reliabilityGrade),
                                      size: 16,
                                    ),
                                  ),
                                  const SizedBox(width: 8),
                                  Expanded(
                                    child: Column(
                                      crossAxisAlignment:
                                          CrossAxisAlignment.start,
                                      children: [
                                        Text(
                                          cand.name,
                                          style: const TextStyle(
                                            fontSize: 12.5,
                                            fontWeight: FontWeight.w900,
                                          ),
                                        ),
                                        Text(
                                          cand.profession,
                                          style: const TextStyle(
                                            fontSize: 10.5,
                                            color: Color(0xFF64748B),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  NeoBrutalBadge(
                                    text: cand.reliabilityGrade,
                                    color:
                                        _getGradeColor(cand.reliabilityGrade),
                                  ),
                                ],
                              ),
                              const SizedBox(height: 8),
                              Row(
                                mainAxisAlignment:
                                    MainAxisAlignment.spaceBetween,
                                children: [
                                  Text(
                                    'Kira: ${CurrencyFormatter.format(cand.monthlyRent)}',
                                    style: const TextStyle(
                                      fontSize: 11,
                                      fontWeight: FontWeight.w800,
                                      color: Color(0xFF10B981),
                                    ),
                                  ),
                                  Text(
                                    'Depozito: ${CurrencyFormatter.format(cand.depositAmount)}',
                                    style: const TextStyle(
                                      fontSize: 11,
                                      fontWeight: FontWeight.w800,
                                    ),
                                  ),
                                  Text(
                                    'Risk: %${cand.evictionRiskScore}',
                                    style: TextStyle(
                                      fontSize: 11,
                                      fontWeight: FontWeight.w800,
                                      color: cand.evictionRiskScore > 15
                                          ? const Color(0xFFEF4444)
                                          : null,
                                    ),
                                  ),
                                ],
                              ),
                              const SizedBox(height: 8),
                              NeoBrutalButton(
                                text: context.tr('rental_btn_lease_now'),
                                backgroundColor: const Color(0xFF10B981),
                                textColor: Colors.white,
                                onPressed: () =>
                                    _leaseToCandidate(cand, prop),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ),
                ],
              ],
            ),
          ),
        ],
      ),
    );
  }

  // --- WIDGET BUILDERS ---

  Widget _buildPropertyHeader(RealEstateModel prop, bool isDark) {
    IconData catIcon;
    switch (prop.category) {
      case RealEstateCategory.land:
        catIcon = Icons.landscape_rounded;
        break;
      case RealEstateCategory.commercial:
        catIcon = Icons.storefront_rounded;
        break;
      case RealEstateCategory.building:
        catIcon = Icons.domain_rounded;
        break;
      case RealEstateCategory.tourismFacility:
        catIcon = Icons.hotel_rounded;
        break;
      case RealEstateCategory.timeshare:
        catIcon = Icons.beach_access_rounded;
        break;
      case RealEstateCategory.housingProjects:
        catIcon = Icons.location_city_rounded;
        break;
      case RealEstateCategory.housing:
        catIcon = Icons.apartment_rounded;
        break;
    }

    return NeoBrutalCard(
      padding: const EdgeInsets.all(14),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(10),
            decoration: BoxDecoration(
              color: const Color(0xFFFFDE59),
              borderRadius: BorderRadius.circular(8),
              border: Border.all(color: Colors.black, width: 2),
            ),
            child: Icon(catIcon, color: Colors.black, size: 24),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  prop.title,
                  style: const TextStyle(
                      fontSize: 14, fontWeight: FontWeight.w900),
                ),
                const SizedBox(height: 2),
                Text(
                  '${prop.city} • ${prop.district} • ${prop.squareMeters} m² • ${prop.roomCount}',
                  style: const TextStyle(
                      fontSize: 11,
                      fontWeight: FontWeight.w600,
                      color: Color(0xFF64748B)),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildFinancialOverviewCard(
    RealEstateModel prop,
    double totalCost,
    double netProfit,
    int profitPercent,
    bool isDark,
  ) {
    return NeoBrutalCard(
      padding: const EdgeInsets.all(14),
      child: Column(
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                context.tr('real_estate_manage_total_cost'),
                style: TextStyle(
                  fontSize: 11.5,
                  color: isDark ? Colors.white60 : Colors.black54,
                  fontWeight: FontWeight.w700,
                ),
              ),
              Text(
                CurrencyFormatter.format(totalCost),
                style: const TextStyle(
                  fontSize: 13,
                  fontWeight: FontWeight.w900,
                ),
              ),
            ],
          ),
          const SizedBox(height: 6),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                context.tr('real_estate_manage_estimated_value'),
                style: TextStyle(
                  fontSize: 11.5,
                  color: isDark ? Colors.white60 : Colors.black54,
                  fontWeight: FontWeight.w700,
                ),
              ),
              Text(
                CurrencyFormatter.format(prop.estimatedRealValue),
                style: const TextStyle(
                  fontSize: 13,
                  fontWeight: FontWeight.w900,
                  color: Color(0xFF2563EB),
                ),
              ),
            ],
          ),
          const Divider(height: 16),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                context.tr('real_estate_expected_arrival_label'),
                style: TextStyle(
                  fontSize: 11.5,
                  color: isDark ? Colors.white60 : Colors.black54,
                  fontWeight: FontWeight.w700,
                ),
              ),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                decoration: BoxDecoration(
                  color: const Color(0xFFEFF6FF),
                  borderRadius: BorderRadius.circular(6),
                  border: Border.all(color: const Color(0xFF2563EB), width: 1.2),
                ),
                child: Text(
                  _getEstimatedWaitLabel(prop),
                  style: const TextStyle(
                    fontSize: 11,
                    fontWeight: FontWeight.w900,
                    color: Color(0xFF1D4ED8),
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildFeaturesSelectionCard(
    List<ListingFeatureGroup> groups,
    bool isDark,
    RealEstateModel prop,
  ) {
    return NeoBrutalCard(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.tune_rounded, size: 18, color: Color(0xFF2563EB)),
              const SizedBox(width: 8),
              Text(
                context.tr('real_estate_listing_features_header'),
                style:
                    const TextStyle(fontSize: 13.5, fontWeight: FontWeight.w900),
              ),
            ],
          ),
          const SizedBox(height: 4),
          Text(
            context.tr('real_estate_listing_features_desc'),
            style: const TextStyle(fontSize: 11, color: Color(0xFF64748B)),
          ),
          const SizedBox(height: 14),
          ...groups.map((group) {
            return Padding(
              padding: const EdgeInsets.only(bottom: 12),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    group.groupTitle,
                    style: TextStyle(
                      fontSize: 11.5,
                      fontWeight: FontWeight.w800,
                      color: isDark ? const Color(0xFF94A3B8) : const Color(0xFF475569),
                    ),
                  ),
                  const SizedBox(height: 6),
                  Wrap(
                    spacing: 8,
                    runSpacing: 8,
                    children: group.features.map((feature) {
                      final isSelected = _selectedFeatures.contains(feature.id);
                      return InkWell(
                        onTap: () {
                          HapticFeedback.selectionClick();
                          setState(() {
                            if (isSelected) {
                              _selectedFeatures.remove(feature.id);
                            } else {
                              _selectedFeatures.add(feature.id);
                            }
                          });
                        },
                        borderRadius: BorderRadius.circular(6),
                        child: AnimatedContainer(
                          duration: const Duration(milliseconds: 150),
                          padding: const EdgeInsets.symmetric(
                              horizontal: 10, vertical: 6),
                          decoration: BoxDecoration(
                            color: isSelected
                                ? const Color(0xFF0F172A)
                                : (isDark
                                    ? const Color(0xFF1E293B)
                                    : Colors.white),
                            borderRadius: BorderRadius.circular(6),
                            border: Border.all(
                              color: Colors.black,
                              width: isSelected ? 2 : 1.5,
                            ),
                            boxShadow: isSelected
                                ? [
                                    const BoxShadow(
                                      color: Color(0xFF10B981),
                                      offset: Offset(2, 2),
                                      blurRadius: 0,
                                    )
                                  ]
                                : null,
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              Icon(
                                isSelected
                                    ? Icons.check_circle_rounded
                                    : feature.icon,
                                size: 14,
                                color: isSelected
                                    ? const Color(0xFF10B981)
                                    : (isDark
                                        ? Colors.white70
                                        : const Color(0xFF334155)),
                              ),
                              const SizedBox(width: 6),
                              Text(
                                feature.label,
                                style: TextStyle(
                                  fontSize: 11,
                                  fontWeight: FontWeight.w800,
                                  color: isSelected
                                      ? Colors.white
                                      : (isDark
                                          ? Colors.white
                                          : Colors.black87),
                                ),
                              ),
                            ],
                          ),
                        ),
                      );
                    }).toList(),
                  ),
                ],
              ),
            );
          }),
        ],
      ),
    );
  }

  Widget _buildHeadlineCard(List<String> presets, bool isDark) {
    return NeoBrutalCard(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.campaign_rounded,
                  size: 18, color: Color(0xFFD97706)),
              const SizedBox(width: 8),
              Text(
                context.tr('real_estate_listing_headline_header'),
                style:
                    const TextStyle(fontSize: 13.5, fontWeight: FontWeight.w900),
              ),
            ],
          ),
          const SizedBox(height: 6),
          Text(
            context.tr('real_estate_listing_headline_preset_label'),
            style: const TextStyle(
                fontSize: 11,
                fontWeight: FontWeight.w700,
                color: Color(0xFF64748B)),
          ),
          const SizedBox(height: 8),
          SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: Row(
              children: presets.map((preset) {
                final isCurrent = _headlineController.text == preset;
                return Padding(
                  padding: const EdgeInsets.only(right: 8),
                  child: InkWell(
                    onTap: () {
                      HapticFeedback.selectionClick();
                      setState(() {
                        _headlineController.text = preset;
                      });
                    },
                    borderRadius: BorderRadius.circular(6),
                    child: Container(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 10, vertical: 6),
                      decoration: BoxDecoration(
                        color: isCurrent
                            ? const Color(0xFFFEF3C7)
                            : (isDark
                                ? const Color(0xFF1E293B)
                                : const Color(0xFFF1F5F9)),
                        borderRadius: BorderRadius.circular(6),
                        border: Border.all(
                          color: isCurrent
                              ? const Color(0xFFD97706)
                              : Colors.black,
                          width: 1.5,
                        ),
                      ),
                      child: Text(
                        preset,
                        style: TextStyle(
                          fontSize: 10.5,
                          fontWeight: FontWeight.w800,
                          color: isCurrent
                              ? const Color(0xFF92400E)
                              : (isDark ? Colors.white70 : Colors.black87),
                        ),
                      ),
                    ),
                  ),
                );
              }).toList(),
            ),
          ),
          const SizedBox(height: 12),
          TextField(
            controller: _headlineController,
            decoration: InputDecoration(
              filled: true,
              fillColor: isDark
                  ? const Color(0xFF0F172A)
                  : const Color(0xFFF8FAFC),
              contentPadding:
                  const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide: const BorderSide(color: Colors.black, width: 2),
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide: const BorderSide(color: Colors.black, width: 2),
              ),
            ),
            style: const TextStyle(fontSize: 12.5, fontWeight: FontWeight.w800),
          ),
        ],
      ),
    );
  }

  Widget _buildDescriptionCard(RealEstateModel prop, bool isDark) {
    return NeoBrutalCard(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Row(
                children: [
                  const Icon(Icons.description_rounded,
                      size: 18, color: Color(0xFF10B981)),
                  const SizedBox(width: 8),
                  Text(
                    context.tr('real_estate_listing_desc_header'),
                    style: const TextStyle(
                        fontSize: 13.5, fontWeight: FontWeight.w900),
                  ),
                ],
              ),
              InkWell(
                onTap: () => _autoGenerateDescription(prop),
                borderRadius: BorderRadius.circular(6),
                child: Container(
                  padding:
                      const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(
                    color: const Color(0xFFD1FAE5),
                    borderRadius: BorderRadius.circular(6),
                    border: Border.all(color: Colors.black, width: 1.5),
                  ),
                  child: Row(
                    children: [
                      const Icon(Icons.auto_awesome_rounded,
                          size: 13, color: Color(0xFF047857)),
                      const SizedBox(width: 4),
                      Text(
                        context.tr('real_estate_listing_desc_auto_generate'),
                        style: const TextStyle(
                          fontSize: 10.5,
                          fontWeight: FontWeight.w900,
                          color: Color(0xFF047857),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 10),
          TextField(
            controller: _descriptionController,
            maxLines: 4,
            decoration: InputDecoration(
              filled: true,
              fillColor: isDark
                  ? const Color(0xFF0F172A)
                  : const Color(0xFFF8FAFC),
              contentPadding: const EdgeInsets.all(12),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide: const BorderSide(color: Colors.black, width: 2),
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide: const BorderSide(color: Colors.black, width: 2),
              ),
            ),
            style: const TextStyle(fontSize: 11.5, height: 1.4),
          ),
        ],
      ),
    );
  }

  Widget _buildPricingStrategyCard(RealEstateModel prop, bool isDark) {
    final totalCost =
        prop.currentPurchasePrice + prop.deedFeePaid + prop.commissionPaid;
    final netProfit = _customPrice - totalCost;
    final profitPercent =
        totalCost > 0 ? ((netProfit / totalCost) * 100).round() : 0;

    return NeoBrutalCard(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.attach_money_rounded,
                  size: 20, color: Color(0xFF10B981)),
              const SizedBox(width: 6),
              Text(
                context.tr('real_estate_listing_strategy_header'),
                style:
                    const TextStyle(fontSize: 13.5, fontWeight: FontWeight.w900),
              ),
            ],
          ),
          const SizedBox(height: 10),

          // 4 Strateji Butonu
          SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: Row(
              children: [
                _buildStrategyChip(
                  label: context.tr('real_estate_strategy_kelepir'),
                  strategyKey: 'kelepir',
                  color: const Color(0xFFD1FAE5),
                  onTap: () => _applyPricingStrategy(prop, 'kelepir'),
                  isDark: isDark,
                ),
                const SizedBox(width: 8),
                _buildStrategyChip(
                  label: context.tr('real_estate_strategy_market'),
                  strategyKey: 'rayic',
                  color: const Color(0xFFEFF6FF),
                  onTap: () => _applyPricingStrategy(prop, 'rayic'),
                  isDark: isDark,
                ),
                const SizedBox(width: 8),
                _buildStrategyChip(
                  label: context.tr('real_estate_strategy_premium'),
                  strategyKey: 'primli',
                  color: const Color(0xFFFEF3C7),
                  onTap: () => _applyPricingStrategy(prop, 'primli'),
                  isDark: isDark,
                ),
                const SizedBox(width: 8),
                _buildStrategyChip(
                  label: context.tr('real_estate_strategy_tok_satici'),
                  strategyKey: 'tok',
                  color: const Color(0xFFFCE7F3),
                  onTap: () => _applyPricingStrategy(prop, 'tok'),
                  isDark: isDark,
                ),
              ],
            ),
          ),
          const SizedBox(height: 14),

          // Fiyat Giriş Alanı
          TextField(
            controller: _priceController,
            keyboardType: TextInputType.number,
            decoration: InputDecoration(
              labelText: context.tr('real_estate_manage_input_label'),
              filled: true,
              fillColor: isDark
                  ? const Color(0xFF0F172A)
                  : const Color(0xFFF8FAFC),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide: const BorderSide(color: Colors.black, width: 2),
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide: const BorderSide(color: Colors.black, width: 2),
              ),
            ),
            style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w900),
            onChanged: (val) {
              final parsed = double.tryParse(val) ?? 0.0;
              setState(() {
                _customPrice = parsed;
              });
            },
          ),
          const SizedBox(height: 12),

          // Canlı Kâr Marjı Göstergesi
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                context.tr('real_estate_manage_est_profit'),
                style:
                    const TextStyle(fontSize: 12, fontWeight: FontWeight.w700),
              ),
              Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                decoration: BoxDecoration(
                  color: netProfit >= 0
                      ? const Color(0xFFD1FAE5)
                      : const Color(0xFFFEE2E2),
                  borderRadius: BorderRadius.circular(6),
                  border: Border.all(
                    color: netProfit >= 0
                        ? const Color(0xFF10B981)
                        : const Color(0xFFEF4444),
                    width: 1.5,
                  ),
                ),
                child: Text(
                  '${netProfit >= 0 ? '+' : ''}${CurrencyFormatter.format(netProfit)} • %$profitPercent',
                  style: TextStyle(
                    fontSize: 11.5,
                    fontWeight: FontWeight.w900,
                    color: netProfit >= 0
                        ? const Color(0xFF065F46)
                        : const Color(0xFF991B1B),
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildStrategyChip({
    required String label,
    required String strategyKey,
    required Color color,
    required VoidCallback onTap,
    required bool isDark,
  }) {
    final isSelected = _selectedStrategy == strategyKey;
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(6),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
        decoration: BoxDecoration(
          color: isSelected
              ? color
              : (isDark ? const Color(0xFF1E293B) : Colors.white),
          borderRadius: BorderRadius.circular(6),
          border: Border.all(
            color: isSelected ? Colors.black : Colors.black45,
            width: isSelected ? 2 : 1.5,
          ),
          boxShadow: isSelected
              ? [
                  const BoxShadow(
                    color: Colors.black,
                    offset: Offset(1.5, 1.5),
                    blurRadius: 0,
                  )
                ]
              : null,
        ),
        child: Text(
          label,
          style: TextStyle(
            fontSize: 11,
            fontWeight: isSelected ? FontWeight.w900 : FontWeight.w700,
            color: isDark && !isSelected ? Colors.white70 : Colors.black,
          ),
        ),
      ),
    );
  }

  Widget _buildMarketingPackagesCard(dynamic game, bool isDark) {
    return NeoBrutalCard(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.workspace_premium_rounded,
                  size: 20, color: Color(0xFF8B5CF6)),
              const SizedBox(width: 8),
              Text(
                context.tr('real_estate_listing_package_header'),
                style:
                    const TextStyle(fontSize: 13.5, fontWeight: FontWeight.w900),
              ),
            ],
          ),
          const SizedBox(height: 12),

          _buildPackageOption(
            packageId: 'standard',
            title: context.tr('real_estate_pkg_standard_title'),
            feeText: 'Ücretsiz',
            description: context.tr('real_estate_pkg_standard_desc'),
            accentColor: const Color(0xFF94A3B8),
            isDark: isDark,
          ),
          const SizedBox(height: 10),

          _buildPackageOption(
            packageId: 'featured',
            title: context.tr('real_estate_pkg_featured_title'),
            feeText: '₺25.000',
            description: context.tr('real_estate_pkg_featured_desc'),
            accentColor: const Color(0xFFF59E0B),
            isDark: isDark,
          ),
          const SizedBox(height: 10),

          _buildPackageOption(
            packageId: 'super',
            title: context.tr('real_estate_pkg_super_title'),
            feeText: '₺60.000',
            description: context.tr('real_estate_pkg_super_desc'),
            accentColor: const Color(0xFF8B5CF6),
            isDark: isDark,
          ),
        ],
      ),
    );
  }

  Widget _buildPackageOption({
    required String packageId,
    required String title,
    required String feeText,
    required String description,
    required Color accentColor,
    required bool isDark,
  }) {
    final isSelected = _selectedPackage == packageId;
    return InkWell(
      onTap: () {
        HapticFeedback.selectionClick();
        setState(() {
          _selectedPackage = packageId;
        });
      },
      borderRadius: BorderRadius.circular(8),
      child: Container(
        padding: const EdgeInsets.all(12),
        decoration: BoxDecoration(
          color: isSelected
              ? accentColor.withValues(alpha: 0.15)
              : (isDark ? const Color(0xFF1E293B) : Colors.white),
          borderRadius: BorderRadius.circular(8),
          border: Border.all(
            color: isSelected ? accentColor : Colors.black,
            width: isSelected ? 2.5 : 1.5,
          ),
          boxShadow: isSelected
              ? [
                  BoxShadow(
                    color: accentColor,
                    offset: const Offset(2, 2),
                    blurRadius: 0,
                  )
                ]
              : null,
        ),
        child: Row(
          children: [
            Icon(
              isSelected
                  ? Icons.radio_button_checked_rounded
                  : Icons.radio_button_unchecked_rounded,
              color: isSelected ? accentColor : Colors.grey,
              size: 20,
            ),
            const SizedBox(width: 10),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        title,
                        style: const TextStyle(
                            fontSize: 12.5, fontWeight: FontWeight.w900),
                      ),
                      Container(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 6, vertical: 2),
                        decoration: BoxDecoration(
                          color: isSelected ? accentColor : Colors.black12,
                          borderRadius: BorderRadius.circular(4),
                        ),
                        child: Text(
                          feeText,
                          style: TextStyle(
                            fontSize: 10.5,
                            fontWeight: FontWeight.w900,
                            color: isSelected ? Colors.white : Colors.black87,
                          ),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 2),
                  Text(
                    description,
                    style: TextStyle(
                      fontSize: 10.5,
                      color: isDark ? Colors.white70 : const Color(0xFF64748B),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildActionButtons(RealEstateModel prop) {
    return Column(
      children: [
        if (prop.isListed && prop.activeOffers.isNotEmpty) ...[
          NeoBrutalButton(
            text:
                '${context.tr('real_estate_btn_view_offers')} • ${prop.activeOffers.length} Teklif',
            backgroundColor: const Color(0xFFF59E0B),
            textColor: Colors.black,
            onPressed: () {
              HapticFeedback.selectionClick();
              RealEstateOffersSheet.show(context: context, property: prop);
            },
          ),
          const SizedBox(height: 10),
        ],
        NeoBrutalButton(
          text: prop.isListed
              ? context.tr('real_estate_manage_btn_update')
              : context.tr('real_estate_btn_list_for_sale'),
          backgroundColor: const Color(0xFF10B981),
          textColor: Colors.white,
          onPressed: () => _publishSaleListing(prop),
        ),
        if (prop.isListed) ...[
          const SizedBox(height: 10),
          NeoBrutalButton(
            text: context.tr('real_estate_manage_btn_unlist'),
            backgroundColor: const Color(0xFFEF4444),
            textColor: Colors.white,
            onPressed: () => _unlistSaleListing(prop),
          ),
        ],
      ],
    );
  }
}
