import 'package:flutter/widgets.dart';

class AppLocalizations {
  final String languageCode;

  const AppLocalizations(this.languageCode);

  static const Map<String, Map<String, String>> _localizedValues = {
    // ==========================================
    // TÜRKÇE (tr)
    // ==========================================
    'tr': {
      'app_name': 'Galeriden',
      'settings_title': 'AYARLAR & PROFİL',
      'language_select': 'Dil Seçeneği',
      'language_desc': 'Arayüz ve oyun dili',
      'theme_store': 'TEMA & GÖRÜNÜM MAĞAZASI',
      'dealership_identity': 'GALERİ & PROFİL KİMLİĞİ',
      'audio_effects': 'Ses Efektleri',
      'audio_desc': 'Motor ve buton sesleri',
      'dashboard': 'GALERİ VİTRİNİ',
      'garage': 'GARAJ & ENVANTER',
      'showroom': 'SHOWROOM & SATIŞ',
      'scrapyard': 'SANAYİ & HURDALIK',
      'stock_market': 'BORSA & YATIRIM',
      'auction': 'GÜMRÜK MÜZAYEDESİ',
      'staff': 'PERSONEL & AKADEMİ',
      'notary': 'NOTER & DEVİR İŞLEMLERİ',
      'bank': 'ESNAF KREDİSİ & MEVDUAT',
      'night_race': 'GECE YARIŞLARI & BAHİS',
      'missions': 'GÖREVLER & BAŞARIMLAR',
      'level': 'Seviye',
      'reputation': 'İtibar',
      'balance': 'Bakiye',
      'day': 'Gün',
      'garage_slots': 'Garaj Kapasitesi',
      'claim': 'ÖDÜLÜ AL',
      'confirm': 'ONAYLA',
      'cancel': 'İPTAL',
      'close': 'KAPAT',
      'save': 'KAYDET',
      'buy': 'SATIN AL',
      'sell': 'SATIŞA ÇIKAR',
      'clean': 'YIKAMA & DETAYLI TEMİZLİK',
      'repair': 'SANAYİ ONARIMI',
      'tuning': 'VIP TUNING STÜDYOSU',
      'inspect': 'EKSPERTİZ RAPORU',
      'streak_title': '28 GÜNLÜK ESNAF TAKVİMİ',
      'streak_ready': 'SİFTAH HAZIR',
      'streak_wait': 'YARIN GEL',
      'streak_claimed': 'ÖDÜL ALINDI',
      'season_spring': 'İLKBAHAR ÇARŞI SEZONU',
      'season_summer': 'YAZ GURBETÇİ SEZONU',
      'season_autumn': 'SONBAHAR SANAYİ SEZONU',
      'season_winter': 'KIŞ GALERİ AĞALIĞI SEZONU',
      'crm_title': 'MÜŞTERİ GERİ BİLDİRİMİ',
      'crm_resolve': 'ESNAF KARARINI VER',
      'bist_glrd': 'BIST: GLRD',
      'company_ipo': 'HALKA ARZ MASASI',
      'share_buyback': 'PİYASADAN HİSSE GERİ AL',
      'quarterly_report': 'ÇEYREKLİK BİLANÇO',
      'bluff_button': 'BLÖF YAP VE ÇEKİL',
      'sanayi_rumor': 'GÜNÜN SANAYİ TÜYOSU',
      'staff_morale': 'Personel Morali',
      'tea_treat': 'ÇAY ISMARLA',
      'meal_treat': 'YEMEK ISMARLA',
      'bonus_treat': 'BAYRAM HARÇLIĞI',
    },

    // ==========================================
    // ENGLISH (en)
    // ==========================================
    'en': {
      'app_name': 'Dealership Tycoon',
      'settings_title': 'SETTINGS & PROFILE',
      'language_select': 'Language Option',
      'language_desc': 'Interface & game language',
      'theme_store': 'THEME & APPEARANCE STORE',
      'dealership_identity': 'DEALERSHIP & PROFILE IDENTITY',
      'audio_effects': 'Sound Effects',
      'audio_desc': 'Engine & button sounds',
      'dashboard': 'DEALERSHIP DASHBOARD',
      'garage': 'GARAGE & INVENTORY',
      'showroom': 'SHOWROOM & SALES',
      'scrapyard': 'SCRAPYARD & WORKSHOP',
      'stock_market': 'STOCK MARKET & INVESTMENTS',
      'auction': 'CUSTOMS AUCTION',
      'staff': 'STAFF & ACADEMY',
      'notary': 'NOTARY & TITLE TRANSFER',
      'bank': 'BUSINESS LOANS & DEPOSITS',
      'night_race': 'NIGHT RACES & BETTING',
      'missions': 'MISSIONS & ACHIEVEMENTS',
      'level': 'Level',
      'reputation': 'Reputation',
      'balance': 'Balance',
      'day': 'Day',
      'garage_slots': 'Garage Capacity',
      'claim': 'CLAIM REWARD',
      'confirm': 'CONFIRM',
      'cancel': 'CANCEL',
      'close': 'CLOSE',
      'save': 'SAVE',
      'buy': 'PURCHASE',
      'sell': 'LIST FOR SALE',
      'clean': 'CAR WASH & DETAILING',
      'repair': 'WORKSHOP REPAIR',
      'tuning': 'VIP TUNING STUDIO',
      'inspect': 'INSPECTION REPORT',
      'streak_title': '28-DAY BUSINESS CALENDAR',
      'streak_ready': 'DAILY REWARD READY',
      'streak_wait': 'COME BACK TOMORROW',
      'streak_claimed': 'CLAIMED',
      'season_spring': 'SPRING MARKET SEASON',
      'season_summer': 'SUMMER TOURISM SEASON',
      'season_autumn': 'AUTUMN FLEET SEASON',
      'season_winter': 'WINTER TYCOON SEASON',
      'crm_title': 'CUSTOMER CRM EVENT',
      'crm_resolve': 'MAKE RESOLUTION',
      'bist_glrd': 'GLRD HOLDING',
      'company_ipo': 'COMPANY IPO DESK',
      'share_buyback': 'BUY BACK SHARES',
      'quarterly_report': 'QUARTERLY EARNINGS',
      'bluff_button': 'BLUFF & BAIL OUT',
      'sanayi_rumor': 'DAILY WORKSHOP RUMOR',
      'staff_morale': 'Staff Morale',
      'tea_treat': 'BUY COFFEE',
      'meal_treat': 'BUY LUNCH',
      'bonus_treat': 'PERFORMANCE BONUS',
    },

    // ==========================================
    // GERMAN (de)
    // ==========================================
    'de': {
      'app_name': 'Autohaus Tycoon',
      'settings_title': 'EINSTELLUNGEN & PROFIL',
      'language_select': 'Sprachauswahl',
      'language_desc': 'Oberflächen- & Spielsprache',
      'theme_store': 'THEMEN & DESIGN-SHOP',
      'dealership_identity': 'AUTOHAUS & PROFILIDENTITÄT',
      'audio_effects': 'Soundeffekte',
      'audio_desc': 'Motor- und Tastengeräusche',
      'dashboard': 'AUTOHAUS SHOWROOM',
      'garage': 'GARAGE & INVENTAR',
      'showroom': 'VERKAUFSRAUM & ANGEBOTE',
      'scrapyard': 'SCHROTTPLATZ & WERKSTATT',
      'stock_market': 'BÖRSE & FINANZEN',
      'auction': 'ZOLL-AUKTION',
      'staff': 'PERSONAL & AKADEMIE',
      'notary': 'ZULASSUNG & VERTRAG',
      'bank': 'GEWERBEKREDIT & EINLAGEN',
      'night_race': 'NACHTRENNEN & WETTEN',
      'missions': 'MISSIONEN & ERFOLGE',
      'level': 'Stufe',
      'reputation': 'Ruf',
      'balance': 'Guthaben',
      'day': 'Tag',
      'garage_slots': 'Garagenkapazität',
      'claim': 'BELOHNUNG ABHOLEN',
      'confirm': 'BESTÄTIGEN',
      'cancel': 'ABBRECHEN',
      'close': 'SCHLIEßEN',
      'save': 'SPEICHERN',
      'buy': 'KAUFEN',
      'sell': 'INSERIEREN',
      'clean': 'AUTOWÄSCHE & AUFBEREITUNG',
      'repair': 'WERKSTATTREPARATUR',
      'tuning': 'VIP-TUNING-STUDIO',
      'inspect': 'TÜV-GUTACHTEN',
      'streak_title': '28-TAGE-GESCHÄFTSKALENDER',
      'streak_ready': 'PRÄMIE BEREIT',
      'streak_wait': 'MORGEN WIEDERKOMMEN',
      'streak_claimed': 'EINGELÖST',
      'season_spring': 'FRÜHLINGS-MARKT-SAISON',
      'season_summer': 'SOMMER-TOURISMUS-SAISON',
      'season_autumn': 'HERBST-FLOTTEN-SAISON',
      'season_winter': 'WINTER-TYCOON-SAISON',
      'crm_title': 'KUNDENBETREUUNG (CRM)',
      'crm_resolve': 'ENTSCHEIDUNG TREFFEN',
      'bist_glrd': 'GLRD HOLDING AG',
      'company_ipo': 'BÖRSENGANG-PULT',
      'share_buyback': 'AKTIENRÜCKKAUF',
      'quarterly_report': 'QUARTALSBERICHT',
      'bluff_button': 'BLUFFEN & AUSSTEIGEN',
      'sanayi_rumor': 'TÄGLICHE WERKSTATT-GERÜCHTE',
      'staff_morale': 'Mitarbeitermoral',
      'tea_treat': 'KAFFEE SPENDIEREN',
      'meal_treat': 'MITTAGESSEN AUSGEBEN',
      'bonus_treat': 'LEISTUNGSBONUS',
    },

    // ==========================================
    // PORTUGUESE (pt - Brasil)
    // ==========================================
    'pt': {
      'app_name': 'Concessionária Tycoon',
      'settings_title': 'CONFIGURAÇÕES & PERFIL',
      'language_select': 'Opção de Idioma',
      'language_desc': 'Idioma da interface e do jogo',
      'theme_store': 'LOJA DE TEMAS & VISUAIS',
      'dealership_identity': 'IDENTIDADE DA LOJA & PERFIL',
      'audio_effects': 'Efeitos Sonoros',
      'audio_desc': 'Sons de motor e botões',
      'dashboard': 'PAINEL DA LOJA',
      'garage': 'GARAGEM & ESTOQUE',
      'showroom': 'SHOWROOM & VENDAS',
      'scrapyard': 'DESMANCHE & OFICINA',
      'stock_market': 'BOLSA & INVESTIMENTOS',
      'auction': 'LEILÃO DA ALFÂNDEGA',
      'staff': 'EQUIPE & ACADEMIA',
      'notary': 'CARTÓRIO & TRANSFERÊNCIA',
      'bank': 'EMPRÉSTIMOS & POUPANÇA',
      'night_race': 'RACHAS NOTURNOS & APOSTAS',
      'missions': 'MISSÕES & CONQUISTAS',
      'level': 'Nível',
      'reputation': 'Reputação',
      'balance': 'Saldo',
      'day': 'Dia',
      'garage_slots': 'Vagas na Garagem',
      'claim': 'RESGATAR RECOMPENSA',
      'confirm': 'CONFIRMAR',
      'cancel': 'CANCELAR',
      'close': 'FECHAR',
      'save': 'SALVAR',
      'buy': 'COMPRAR',
      'sell': 'COLOCAR À VENDA',
      'clean': 'LAVA-RÁPIDO & POLIMENTO',
      'repair': 'REPARO NA OFICINA',
      'tuning': 'ESTÚDIO VIP DE TUNING',
      'inspect': 'LAUDO CAUTELAR',
      'streak_title': 'CALENDÁRIO DE 28 DIAS',
      'streak_ready': 'RECOMPENSA PRONTA',
      'streak_wait': 'VOLTE AMANHÃ',
      'streak_claimed': 'RESGATADO',
      'season_spring': 'TEMPORADA DE PRIMAVERA',
      'season_summer': 'TEMPORADA DE VERÃO',
      'season_autumn': 'TEMPORADA DE OUTONO',
      'season_winter': 'TEMPORADA DE INVERNO',
      'crm_title': 'EVENTO DE PÓS-VENDA (CRM)',
      'crm_resolve': 'TOMAR DECISÃO',
      'bist_glrd': 'GLRD HOLDING',
      'company_ipo': 'MESA DE IPO / BOLSA',
      'share_buyback': 'RECOMPRAR AÇÕES',
      'quarterly_report': 'BALANÇO TRIMESTRAL',
      'bluff_button': 'BLEFAR E SAIR',
      'sanayi_rumor': 'FOFOCA DO DIA NO DESMANCHE',
      'staff_morale': 'Moral dos Funcionários',
      'tea_treat': 'PAGAR CAFÉ',
      'meal_treat': 'PAGAR ALMOÇO',
      'bonus_treat': 'BÔNUS SALARIAL',
    },

    // ==========================================
    // SPANISH (es)
    // ==========================================
    'es': {
      'app_name': 'Concesionario Tycoon',
      'settings_title': 'AJUSTES & PERFIL',
      'language_select': 'Opción de Idioma',
      'language_desc': 'Idioma de interfaz y juego',
      'theme_store': 'TIENDA DE TEMAS & DISEÑO',
      'dealership_identity': 'CONCESIONARIO & PERFIL',
      'audio_effects': 'Efectos de Sonido',
      'audio_desc': 'Sonidos de motor y botones',
      'dashboard': 'PANEL DEL CONCESIONARIO',
      'garage': 'GARAJE & INVENTARIO',
      'showroom': 'SHOWROOM & VENTAS',
      'scrapyard': 'DESGUACE & TALLER',
      'stock_market': 'BOLSA & INVERSIONES',
      'auction': 'SUBASTA DE ADUANAS',
      'staff': 'PERSONAL & ACADEMIA',
      'notary': 'NOTARÍA & TRASPASO',
      'bank': 'CRÉDITOS & DEPÓSITOS',
      'night_race': 'CARRERAS NOCTURNAS & APUESTAS',
      'missions': 'MISIONES & LOGROS',
      'level': 'Nivel',
      'reputation': 'Reputación',
      'balance': 'Saldo',
      'day': 'Día',
      'garage_slots': 'Plazas de Garaje',
      'claim': 'RECLAMAR RECOMPENSA',
      'confirm': 'CONFIRMAR',
      'cancel': 'CANCELAR',
      'close': 'CERRAR',
      'save': 'GUARDAR',
      'buy': 'COMPRAR',
      'sell': 'PONER A LA VENTA',
      'clean': 'LAVADO & PULIDO',
      'repair': 'REPARACIÓN EN TALLER',
      'tuning': 'ESTUDIO VIP DE TUNING',
      'inspect': 'INFORME DE PERITAJE',
      'streak_title': 'CALENDARIO DE 28 DÍAS',
      'streak_ready': 'RECOMPENSA LISTA',
      'streak_wait': 'VUELVE MAÑANA',
      'streak_claimed': 'RECLAMADO',
      'season_spring': 'TEMPORADA DE PRIMAVERA',
      'season_summer': 'TEMPORADA DE VERANO',
      'season_autumn': 'TEMPORADA DE OTOÑO',
      'season_winter': 'TEMPORADA DE INVIERNO',
      'crm_title': 'EVENTO POSVENTA (CRM)',
      'crm_resolve': 'TOMAR DECISIÓN',
      'bist_glrd': 'GLRD HOLDING',
      'company_ipo': 'SALIDA A BOLSA (IPO)',
      'share_buyback': 'RECOMPRA DE ACCIONES',
      'quarterly_report': 'INFORME TRIMESTRAL',
      'bluff_button': 'FAROLEAR Y RETIRARSE',
      'sanayi_rumor': 'RUMOR DEL DÍA EN EL TALLER',
      'staff_morale': 'Moral del Personal',
      'tea_treat': 'INVITAR CAFÉ',
      'meal_treat': 'INVITAR ALMUERZO',
      'bonus_treat': 'BONO DE RENDIMIENTO',
    },

    // ==========================================
    // RUSSIAN (ru)
    // ==========================================
    'ru': {
      'app_name': 'Автосалон Тайкун',
      'settings_title': 'НАСТРОЙКИ И ПРОФИЛЬ',
      'language_select': 'Выбор языка',
      'language_desc': 'Язык интерфейса и игры',
      'theme_store': 'МАГАЗИН ТЕМ И ОФОРМЛЕНИЯ',
      'dealership_identity': 'ПРОФИЛЬ АВТОСАЛОНА',
      'audio_effects': 'Звуковые эффекты',
      'audio_desc': 'Звуки двигателя и кнопок',
      'dashboard': 'ВИТРИНА АВТОСАЛОНА',
      'garage': 'ГАРАЖ И ИНВЕНТАРЬ',
      'showroom': 'ШОУРУМ И ПРОДАЖИ',
      'scrapyard': 'АВТОРАЗБОРКА И СЕРВИС',
      'stock_market': 'БИРЖА И ИНВЕСТИЦИИ',
      'auction': 'ТАМОЖЕННЫЙ АУКЦИОН',
      'staff': 'ПЕРСОНАЛ И АКАДЕМИЯ',
      'notary': 'НОТАРИУС И ОФОРМЛЕНИЕ',
      'bank': 'КРЕДИТЫ И ВКЛАДЫ',
      'night_race': 'НОЧНЫЕ ГОНКИ И СТАВКИ',
      'missions': 'ЗАДАНИЯ И ДОСТИЖЕНИЯ',
      'level': 'Уровень',
      'reputation': 'Репутация',
      'balance': 'Баланс',
      'day': 'День',
      'garage_slots': 'Вместимость гаража',
      'claim': 'ЗАБРАТЬ НАГРАДУ',
      'confirm': 'ПОДТВЕРДИТЬ',
      'cancel': 'ОТМЕНА',
      'close': 'ЗАКРЫТЬ',
      'save': 'СОХРАНИТЬ',
      'buy': 'КУПИТЬ',
      'sell': 'ВЫСТАВИТЬ НА ПРОДАЖУ',
      'clean': 'МОЙКА И ДЕТЕЙЛИНГ',
      'repair': 'РЕМОНТ В СЕРВИСЕ',
      'tuning': 'VIP ТЮНИНГ СТУДИЯ',
      'inspect': 'ТЕХНИЧЕСКИЙ ОСМОТР',
      'streak_title': '28-ДНЕВНЫЙ КАЛЕНДАРЬ',
      'streak_ready': 'НАГРАДА ГОТОВА',
      'streak_wait': 'ПРИХОДИТЕ ЗАВТРА',
      'streak_claimed': 'ПОЛУЧЕНО',
      'season_spring': 'ВЕСЕННИЙ СЕЗОН',
      'season_summer': 'ЛЕТНИЙ ТУРИСТИЧЕСКИЙ СЕЗОН',
      'season_autumn': 'ОСЕННИЙ СЕЗОН АВТОПАРКОВ',
      'season_winter': 'ЗИМНИЙ МАГНАТСКИЙ СЕЗОН',
      'crm_title': 'ОБСЛУЖИВАНИЕ КЛИЕНТОВ (CRM)',
      'crm_resolve': 'ПРИНЯТЬ РЕШЕНИЕ',
      'bist_glrd': 'GLRD ХОЛДИНГ',
      'company_ipo': 'ВЫХОД НА БИРЖУ (IPO)',
      'share_buyback': 'ОБРАТНЫЙ ВЫКУП АКЦИЙ',
      'quarterly_report': 'КВАРТАЛЬНЫЙ ОТЧЕТ',
      'bluff_button': 'БЛЕФОВАТЬ И ВЫЙТИ',
      'sanayi_rumor': 'СЛУХ ДНЯ В АВТОСЕРВИСЕ',
      'staff_morale': 'Боевой дух персонала',
      'tea_treat': 'УГОСТИТЬ ЧАЕМ',
      'meal_treat': 'УГОСТИТЬ ОБЕДОМ',
      'bonus_treat': 'ПРЕМИЯ ЗА РАБОТУ',
    },

    // ==========================================
    // ARABIC (ar)
    // ==========================================
    'ar': {
      'app_name': 'تاجر السيارات الفاخرة',
      'settings_title': 'الإعدادات والملف الشخصي',
      'language_select': 'اختيار اللغة',
      'language_desc': 'لغة الواجهة واللعبة',
      'theme_store': 'متجر المظاهر والتصميم',
      'dealership_identity': 'هوية المعرض والملف الشخصي',
      'audio_effects': 'المؤثرات الصوتية',
      'audio_desc': 'أصوات المحرك والأزرار',
      'dashboard': 'واجهة المعرض الرئيسية',
      'garage': 'المرآب والمخزون',
      'showroom': 'صالة العرض والمبيعات',
      'scrapyard': 'التشليح والورشة',
      'stock_market': 'البورصة والاستثمار',
      'auction': 'مزاد الجمارك للسيارات',
      'staff': 'الموظفون والأكاديمية',
      'notary': 'التوثيق ونقل الملكية',
      'bank': 'القروض التجارية والودائع',
      'night_race': 'سباقات الشوارع الليلية',
      'missions': 'المهام والإنجازات',
      'level': 'المستوى',
      'reputation': 'السمعة',
      'balance': 'الرصيد',
      'day': 'اليوم',
      'garage_slots': 'سعة المرآب',
      'claim': 'استلام المكافأة',
      'confirm': 'تأكيد',
      'cancel': 'إلغاء',
      'close': 'إغلاق',
      'save': 'حفظ',
      'buy': 'شراء',
      'sell': 'عرض للبيع',
      'clean': 'غسيل وتلميع شامل',
      'repair': 'إصلاح في الورشة',
      'tuning': 'استوديو التعديل الاحترافي',
      'inspect': 'تقرير الفحص الفني',
      'streak_title': 'تقويم التاجر لمدة 28 يوما',
      'streak_ready': 'المكافأة جاهزة',
      'streak_wait': 'عد غدا',
      'streak_claimed': 'تم الاستلام',
      'season_spring': 'موسم الربيع التجاري',
      'season_summer': 'موسم الصيف السياحي',
      'season_autumn': 'موسم الخريف والشاحنات',
      'season_winter': 'موسم الشتاء للأثرياء',
      'crm_title': 'خدمة العملاء وما بعد البيع',
      'crm_resolve': 'اتخاذ القرار',
      'bist_glrd': 'مجموعة GLRD القابضة',
      'company_ipo': 'طرح الشركة في البورصة',
      'share_buyback': 'إعادة شراء الأسهم',
      'quarterly_report': 'التقرير المالي الفصلي',
      'bluff_button': 'المراوغة والانسحاب',
      'sanayi_rumor': 'شائعة اليوم في الورشة',
      'staff_morale': 'معنويات الفريق',
      'tea_treat': 'ضيافة الشاي والقهوة',
      'meal_treat': 'ضيافة وجبة الغداء',
      'bonus_treat': 'مكافأة الأداء',
    },
  };

  String get(String key, [Map<String, dynamic>? params]) {
    String? translation = _localizedValues[languageCode]?[key];
    if (translation == null || translation.isEmpty) {
      // Fallback to English, then Turkish
      translation = _localizedValues['en']?[key] ?? _localizedValues['tr']?[key] ?? key;
    }

    if (params != null && params.isNotEmpty) {
      params.forEach((paramKey, value) {
        translation = translation!.replaceAll('{$paramKey}', value.toString());
      });
    }

    return translation!;
  }

  static AppLocalizations of(BuildContext context) {
    // In real widget tree, can read from locale or settings
    final locale = Localizations.maybeLocaleOf(context);
    final code = locale?.languageCode ?? 'tr';
    return AppLocalizations(code);
  }

  static String tr(BuildContext context, String key, [Map<String, dynamic>? params]) {
    return of(context).get(key, params);
  }

  static Map<String, String> getAllKeysFor(String code) {
    return _localizedValues[code] ?? _localizedValues['tr']!;
  }

  static List<String> get supportedLanguageCodes => _localizedValues.keys.toList();
}

extension AppLocalizationExtension on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
  String tr(String key, [Map<String, dynamic>? params]) => AppLocalizations.tr(this, key, params);
}
